name: Node Publish

on:
  workflow_dispatch:

jobs:
  publish_gh:
    runs-on: ubuntu-latest

    concurrency:
      group: publish-gh-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: write

    env:
      CI: true

    outputs:
      pkg_name: ${{ steps.pkg.outputs.pkg }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stoe'

      - name: npm install
        run: |
          npm set-script prepare ""
          npm install --ignore-scripts --pure-lockfile
          git ls-files -z . | xargs -0 git update-index --assume-unchanged

      - name: npm package name
        id: pkg
        run: |
          echo "::set-output name=pkg::$(npm run env | \
            grep 'npm_package_name' | \
            awk -F "=" '{print $2}')"

  delete_old_packages:
    runs-on: ubuntu-latest

    needs: [publish_gh]
    if: always()

    permissions:
      contents: read
      packages: write

    env:
      CI: true

    steps:
      - uses: actions/delete-package-versions@v3
        with:
          package-name: ${{ needs.publish_gh.outputs.pkg_name }}
          min-versions-to-keep: 2
          token: ${{ secrets.GITHUB_TOKEN }}
